# Generated by Django 5.0.5 on 2024-05-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('uzmanlik_alani', models.CharField(max_length=100)),
                ('calistigi_hastane', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doktor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hastalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('dogum_tarihi', models.DateField()),
                ('cinsiyet', models.CharField(max_length=10)),
                ('telefon', models.CharField(max_length=15)),
                ('adres', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randevu_tarihi', models.DateField()),
                ('randevu_saati', models.TimeField()),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.doktorlar')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.hastalar')),
            ],
        ),
        migrations.CreateModel(
            name='TıbbiRaporlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_tarihi', models.DateField()),
                ('rapor_icerigi', models.TextField()),
                ('rapor_gorseli', models.ImageField(blank=True, null=True, upload_to='raporlar/')),
                ('rapor_json', models.JSONField()),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.doktorlar')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.hastalar')),
            ],
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yonetici', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
