# Generated by Django 5.0.5 on 2024-05-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_hastalar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastalar',
            name='user',
        ),
        migrations.AddField(
            model_name='hastalar',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
