# Generated by Django 5.0.5 on 2024-05-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_remove_hastalar_user_hastalar_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hastalar',
            old_name='user_id',
            new_name='user',
        ),
    ]
