# Generated by Django 5.0.5 on 2024-05-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_rename_user_id_hastalar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hastalar',
            old_name='user',
            new_name='user_id',
        ),
    ]
