# Generated by Django 5.0.5 on 2024-05-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_rename_user_hastalar_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastalar',
            name='user_id',
        ),
    ]
