# Generated by Django 5.0.5 on 2024-05-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_remove_hastalar_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktorlar',
            name='user',
        ),
    ]
