# Generated by Django 5.0.5 on 2024-05-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_alter_doktorlar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktorlar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hastalar',
            name='user',
        ),
    ]
