# Generated by Django 5.0.5 on 2024-05-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_hastalar_kullanici_adi_hastalar_sifre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doktorlar',
            name='kullanici_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktorlar',
            name='sifre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doktorlar',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doktor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hastalar',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hasta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hastalar',
            name='kullanici_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hastalar',
            name='sifre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
