# Generated by Django 5.0.5 on 2024-05-17 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_doktorlar_kullanici_adi_doktorlar_sifre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktorlar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doktor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hastalar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasta', to=settings.AUTH_USER_MODEL),
        ),
    ]
